services:
  grafana:
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  otel-col:
    command:
      - --config
      - config.yaml
    image: otel/opentelemetry-collector-contrib:0.102.1
    ports:
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ./otel-col.yaml:/config.yaml

  loki:
    command:
      - -config.file=/etc/loki/local-config.yaml
    image: grafana/loki:2.9.0
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml

  prometheus:
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    image: prom/prometheus:v2.46.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml

  tempo:
    command:
      - -config.file=/etc/tempo.yaml
    image: grafana/tempo:2.4.2
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /tmp/tempo
