networks:
  local_otel:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1

services:
  grafana:
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
    image: grafana/grafana:9.4.3
    networks:
      - local_otel
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  loki:
    command:
      - -config.file=/etc/loki/local-config.yaml
    image: grafana/loki:2.9.0
    networks:
      - local_otel
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml

  prometheus:
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    image: prom/prometheus:v2.46.0
    networks:
      - local_otel
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml

  tempo:
    command:
      - -config.file=/etc/tempo.yaml
    image: grafana/tempo:2.2.3
    networks:
      - local_otel
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /tmp/tempo
